### ISSUE TITLE
Basics of Networking

### ISSUE THREAD

**Issue by sidd4698** [sidd4698/training#2]
@davidrcyril  follow tutorial on the links 
- [x] TCP https://en.wikipedia.org/wiki/Internet_protocol_suite 
- [x] Sockets http://www.tutorialspoint.com/java/java_networking.htm

**Comment by sidd4698** [comment]
@davidrcyril 
Tasks
1. Clone the repo
2. Create a source file trainserver.java and trainclient.java
3. write a program to send and receive messages in text using socket programming

**Comment by sidd4698** [comment]
@davidrcyril paste the command prompt messages here

**Comment by davidrcyril** [comment]
00000002.regtrans-ms
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TM.blf
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TMContainer000000000000
00000001.regtrans-ms
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TMContainer000000000000
00000002.regtrans-ms
        Pictures/
        Saved Games/
        Searches/
        SkyDrive.old/
        SkyDrive/
        Tracing/
        Videos/
        WebstormProjects/
        eclipse/
        holidaytesting/
        ntuser.dat.LOG1
        ntuser.dat.LOG2
        ntuser.ini
        training/
        workspace/

nothing added to commit but untracked files present

C:\Users\Admin>git log
commit aa4c9a3dabce11ee0c196276c4d9de0e10baf4ed
Author: davidrcyril <david@fyrsta.org>
Date:   Sat Jan 23 12:36:34 2016 +0530

    Two Java programs are added

C:\Users\Admin>git remote add origin https://github.com/sid4698/training.git

C:\Users\Admin>git push master
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

C:\Users\Admin>git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master


C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sid4698/training.git/'

C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sid4698/training.git/'

C:\Users\Admin>git push origin master
Username for 'https://github.com':
Password for 'https://@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sid4698/training.git/'

C:\Users\Admin>
C:\Users\Admin>git clone https://github.com/sid4698/training.git
fatal: destination path 'training' already exists and is not an empty directory.


C:\Users\Admin>git add trainserver.java trainclient.java

C:\Users\Admin>git commit -m "Java programs are added"
On branch master
Untracked files:
        .AndroidStudio1.2/
        .WebStorm10/
        .android/
        .bash_history
        .bluemix/
        .cf/
        .eclipse/
        .gitconfig
        .gradle/
        .jssc/
        .node_repl_history
        .oracle_jre_usage/
        .p2/
        AndroidStudioProjects/
        AppData/
        Contacts/
        Desktop/
        Documents/
        Downloads/
        Dropbox/
        EvothingsStudio/
        Favorites/
        IntelGraphicsProfiles/
        Links/
        Music/
        NTUSER.DAT
        NTUSER.DAT{889d499b-0b5e-11e3-93f9-90b11c1ccade}.TM.blf
        NTUSER.DAT{889d499b-0b5e-11e3-93f9-90b11c1ccade}.TMContainer000000000000
00000001.regtrans-ms
        NTUSER.DAT{889d499b-0b5e-11e3-93f9-90b11c1ccade}.TMContainer000000000000
00000002.regtrans-ms
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TM.blf
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TMContainer000000000000
00000001.regtrans-ms
        NTUSER.DAT{fb3f083c-8a7f-11e4-825a-4cbb5814a919}.TMContainer000000000000
00000002.regtrans-ms
        Pictures/
        Saved Games/
        Searches/
        SkyDrive.old/
        SkyDrive/
        Tracing/
        Videos/
        WebstormProjects/
        eclipse/
        holidaytesting/
        ntuser.dat.LOG1
        ntuser.dat.LOG2
        ntuser.ini
        training/
        workspace/

nothing added to commit but untracked files present

C:\Users\Admin>git log
commit aa4c9a3dabce11ee0c196276c4d9de0e10baf4ed
Author: davidrcyril <david@fyrsta.org>
Date:   Sat Jan 23 12:36:34 2016 +0530

    Two Java programs are added

C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sid4698/training.git/'

C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sid4698/training.git/'

C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/sid4698/training.git/' not found

C:\Users\Admin>git push origin master
Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/sid4698/training.git/' not found

C:\Users\Admin>training
'training' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Admin>training
'training' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Admin>cd training

C:\Users\Admin\training>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        trainclient.java
        trainserver.java

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\Admin\training>git add .

C:\Users\Admin\training>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   trainclient.java
        new file:   trainserver.java


C:\Users\Admin\training>git commit -m "message"
[master 91bf486] message
 2 files changed, 36 insertions(+)
 create mode 100644 trainclient.java
 create mode 100644 trainserver.java

C:\Users\Admin\training>git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was@github.com':  Git 1.7.11. Use the similar mode
remote: Invalid username or password.sometimes use older versions of Git)
fatal: Authentication failed for 'https://github.com/sidd4698/training.git/'
Username for 'https://github.com':
C:\Users\Admin\training>g
'g' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Admin\training>gdacidrcyril
'gdacidrcyril' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Admin\training>git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Username for 'https://github.com': davidrcyril
Password for 'https://davidrcyril@github.com':
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/sidd4698/training.git/'

C:\Users\Admin\training>git pus

**Comment by sidd4698** [comment]
@davidrcyril Follow this

When using the https:// URL to connect to your remote repository, then Git will not use SSH as authentication but will instead try a basic authentication over HTTPS. Usually, you would just use the URL without a username, e.g. https://github.com/username/repository.git, and Git would then prompt you to enter both a username (your GitHub username) and your password.

If you use https://something@github.com/username/repository.git, then you have preset the username Git will use for authentication: something. Since you used https://git@github.com, Git will try to log in using the git username for which your password of course doesn’t work. So you will have to use your username instead.

The alternative is actually to use SSH for authentication. That way you will avoid having to type your password all the time; and since it already seems to work, that’s what you should be using.

To do that, you need to change your remote URL though, so Git knows that it needs to connect via SSH. The format is then this: git@github.com:username/repository. To update your URL use this command:

git remote set-url origin git@github.com:username/repository

**Comment by sidd4698** [comment]
@davidrcyril this clearly explains the issue http://stackoverflow.com/questions/20913962/github-authentication-failing-over-https-returning-wrong-email-address
